<?php

namespace Website\AdminBundle\Repository;
use Doctrine\ORM\Query;

/**
 * PresentationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PresentationRepository extends \Doctrine\ORM\EntityRepository
{

}
