<?php

namespace Website\AdminBundle\Repository;

/**
 * PresentationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PresentationRepository extends \Doctrine\ORM\EntityRepository
{
	public function getPresentation($locale){
		$sql = $this->getEntityManager()
		->createQuery("SELECT pt.description FROM WebsiteAdminBundle:Presentation p JOIN WebsiteAdminBundle:PresentationTraduction pt WHERE p.id = pt.presentation_id AND pt.locale = :locale ")
		->setParameter('locale',$locale);
		$presentation =  $sql->getResult();
		return $presentation[0];
	}
}
