<?php

namespace Website\AdminBundle\Repository;

/**
 * PresentationTraductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PresentationTraductionRepository extends \Doctrine\ORM\EntityRepository
{
}
